<?php

$nom = $_POST['h_nom'];
$prenom = $_POST['h_prenom'];
$date_entree = $_POST["h_date_entree"];
$date_sortie = $_POST["h_date_sortie"];
$matricule = $_POST['h_matricule'];
$badge = $_POST['h_badge'];
$contrat = $_POST['h_contrat'];
$service = $_POST['h_service'];
$section_analytique = $_POST['h_section_analytique'];
$superieur = $_POST['h_superieur'];
$fixe = $_POST['h_fixe'];
$dect = $_POST['h_dect'];
$apple = $_POST['h_dect'];
$android = $_POST['h_android'];
$pc = $_POST['h_pc'];
$laptop = $_POST['h_laptop'];
$surface = $_POST['h_surface'];
$reaffectation = $_POST['h_reaffectation'];
$brassage = $_POST['h_brassage'];
$email = $_POST['h_email'];
$internet = $_POST['h_internet'];
$sap = $_POST['h_sap'];
$licence_sap = $_POST['h_licence_sap'];
$articles_be = $_POST['h_articles_be'];
$groups = $_POST['h_groups'];
$impr = $_POST['h_impr'];
$softs = $_POST['h_softs'];
$droits = $_POST['h_droits'];


require('fpdf.php'); 

$pdf = new FPDF();
// Chargement des données
$pdf->AddPage();
$pdf->SetFont('Arial','IB',10);
$pdf->Cell(0,5,"FORMULAIRE D'ENTREE",0,1, 'C');
$pdf->Cell(1,5,'',0,1);
$pdf->SetFont('Arial','U',10);
$pdf->Cell(2,5,'INFOS SUR LA PERSONNE',0,1);
$pdf->Cell(3,5,'',0,1);
$pdf->SetFont('Arial','',10);
$pdf->Cell(4,5,utf8_decode('Nom : '.$nom),0,1);
$pdf->Cell(5,5,utf8_decode('Prénom : '.$prenom),0,1);
$pdf->Cell(6,5,utf8_decode("Date d'entrée : ".$date_entree),0,1);
$pdf->Cell(7,5,utf8_decode('Date sortie : '.$date_sortie),0,1);
$pdf->Cell(8,5,utf8_decode('Matricule : '.$matricule),0,1);
$pdf->Cell(9,5,utf8_decode('Num Badge : '.$badge),0,1);
$pdf->Cell(10,5,utf8_decode('Type de contrat: '.$contrat),0,1);
$pdf->Cell(11,5,utf8_decode('Service : '.$service),0,1);
$pdf->Cell(12,5,utf8_decode('Section analytique : '.$section_analytique),0,1);
$pdf->Cell(13,5,utf8_decode('Supérieur hiérarchique : '.$superieur),0,1);
$pdf->Cell(14,5,'',0,1);
$pdf->SetFont('Arial','U',10);
$pdf->Cell(15,5,'EQUIPEMENTS',0,1);
$pdf->Cell(16,5,'',0,1);
$pdf->SetFont('Arial','',10);
$pdf->Cell(17,5,utf8_decode('Téléphone fixe: '.$fixe),0,1);
$pdf->Cell(18,5,'DECT: '.$dect,0,1);
$pdf->Cell(19,5,'Apple: '.$apple,0,1);
$pdf->Cell(20,5,'Android: '.$android,0,1);
$pdf->Cell(21,5,'PC: '.$pc,0,1);
$pdf->Cell(22,5,'Laptop: '.$laptop,0,1);
$pdf->Cell(23,5,'Surface: '.$surface,0,1);
$pdf->Cell(24,5,utf8_decode("Réutilisation d'un matériel existant: ".$reaffectation),0,1);
$pdf->Cell(25,5,'',0,1);
$pdf->SetFont('Arial','U',10);
$pdf->Cell(26,5,'CONFIG INFORMATIQUE',0,1,"U");
$pdf->Cell(27,5,'',0,1);
$pdf->SetFont('Arial','',10);
$pdf->Cell(28,5,utf8_decode('Prise murale à connecter: '.$brassage),0,1);
$pdf->Cell(29,5,utf8_decode('Création boite Email: '.$email),0,1);
$pdf->Cell(30,5,utf8_decode('Accès Internet: '.$internet),0,1);
$pdf->Cell(31,5,utf8_decode('Installation SAP: '.$sap),0,1);
$pdf->Cell(32,5,utf8_decode('Nouvelle licence SAP: '.$licence_sap),0,1);
$pdf->Cell(33,5,utf8_decode('Installation plans articles BE: '.$articles_be),0,1);
$pdf->Cell(34,5,'',0,1);
$pdf->SetFont('Arial','U',10);
$pdf->Cell(35,5,'GROUPE(S)',0,1);
$pdf->Cell(36,5,'',0,1);
$pdf->SetFont('Arial','',10);
$pdf->Cell(37,5,utf8_decode('Ajouter aux groupes: '.$groups),0,1);
$pdf->Cell(38,5,'',0,1);
$pdf->SetFont('Arial','U',10);
$pdf->Cell(39,5,'IMPRIMANTE(S)',0,1);
$pdf->Cell(40,5,'',0,1);
$pdf->SetFont('Arial','',10);
$pdf->MultiCell(0,5,utf8_decode('Imprimantes a configurer : ' .$impr),0,1);
$pdf->Cell(42,5,'',0,1);
$pdf->SetFont('Arial','U',10);
$pdf->Cell(43,5,'AUTRE(S) LOGICIEL(S)',0,1);
$pdf->Cell(44,5,'',0,1);
$pdf->SetFont('Arial','',10);
$pdf->Cell(45,5,utf8_decode('Logiciels à installer : '.$softs),0,1);
$pdf->Cell(46,5,'',0,1);
$pdf->SetFont('Arial','U',10);
$pdf->Cell(47,5,'DROITS ACCES DOSSIER(S)',0,1);
$pdf->Cell(48,5,'',0,1);
$pdf->SetFont('Arial','',10);
$pdf->Cell(49,5,utf8_decode("Droits d'accès aux dossiers : ".$droits),0,1);
$pdf->Output("D", "formulaire_".$nom."_".$prenom."_entree.pdf");
?>